services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.136.0@sha256:45392d534c1edcc809c2d112394029246bc679d2ae5ea7081414a1fc74f2c621
    command: ["--config=/etc/otel/config.yaml"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./collector.yaml:/etc/otel/config.yaml:ro
    ports:
      - "4517:4317"
      - "4518:4318"
