events {}
http {
  server {
    listen 9243 ssl;
    ssl_certificate /certs/server.pem;
    ssl_certificate_key /certs/server.key;
    ssl_client_certificate /certs/ca.pem;
    ssl_verify_client on;
    location / {
      proxy_pass http://host.docker.internal:9200;
      proxy_set_header Host $host;
    }
  }
}
