services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.103.0@sha256:0dffde3e58fc3f255cad861deb62d7c51505ce961a8a7e2107c7fc2668b774a3
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./config.yaml:/etc/otel/config.yaml:ro
      - ./out:/out
    ports:
      - "4417:4317"
      - "4418:4318"
