"use strict";

const { FIXTURE_HOST } = require("./catalog.cjs");

const workload = { uid: 1000, pid: 7 };

const CASES = [
  {
    id: "files-open-exact",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "/etc/crontab", ...workload },
    expect: { disposition: "DENIED_BY_CITED_MECHANISM", mechanism_id: "path_deny_kprobes", effect: "EACCES" },
  },
  {
    id: "files-openat-exact",
    surface: "files",
    attempt: { surface: "files", op: "openat", path: "/etc/crontab", ...workload },
    expect: { disposition: "DENIED_BY_CITED_MECHANISM", mechanism_id: "path_deny_kprobes", effect: "EACCES" },
  },
  {
    id: "files-openat2-best-effort",
    surface: "files",
    attempt: { surface: "files", op: "openat2", path: "/etc/crontab", ...workload },
    expect: { disposition: "BEST_EFFORT_NOT_PROVED", decision_if_attached: "EACCES", mechanism_id: "path_deny_kprobes" },
  },
  {
    id: "files-creat-dir",
    surface: "files",
    attempt: { surface: "files", op: "creat", path: "/var/lib/vantio-proof/new", ...workload },
    expect: { disposition: "BEST_EFFORT_NOT_PROVED", decision_if_attached: "EACCES" },
  },
  {
    id: "files-truncate",
    surface: "files",
    attempt: { surface: "files", op: "truncate", path: "/etc/crontab", ...workload },
    expect: { disposition: "BEST_EFFORT_NOT_PROVED", decision_if_attached: "EACCES" },
  },
  {
    id: "files-rename",
    surface: "files",
    attempt: { surface: "files", op: "rename", path: "/etc/crontab", path2: "/tmp/moved", ...workload },
    expect: { disposition: "BEST_EFFORT_NOT_PROVED", decision_if_attached: "EACCES" },
  },
  {
    id: "files-unlink",
    surface: "files",
    attempt: { surface: "files", op: "unlink", path: "/etc/crontab", ...workload },
    expect: { disposition: "BEST_EFFORT_NOT_PROVED", decision_if_attached: "EACCES" },
  },
  {
    id: "files-link",
    surface: "files",
    attempt: { surface: "files", op: "link", path: "/etc/crontab", path2: "/tmp/hard", ...workload },
    expect: { disposition: "BEST_EFFORT_NOT_PROVED", decision_if_attached: "EACCES" },
  },
  {
    id: "files-symlink",
    surface: "files",
    attempt: { surface: "files", op: "symlink", path: "/etc/crontab", path2: "/tmp/link", ...workload },
    expect: { disposition: "BEST_EFFORT_NOT_PROVED", decision_if_attached: "EACCES" },
  },
  {
    id: "files-uid0",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "/etc/crontab", uid: 0, pid: 1 },
    expect: { disposition: "NAMED_RESIDUAL", residual: "uid_0_excluded" },
  },
  {
    id: "files-loader-tgid",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "/etc/crontab", uid: 1000, pid: FIXTURE_HOST.loader_tgid },
    expect: { disposition: "NAMED_RESIDUAL", residual: "loader_tgid_excluded" },
  },
  {
    id: "files-unlisted",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "/tmp/unlisted", ...workload },
    expect: { disposition: "NOT_COVERED", reason: "path_not_in_enforce_maps" },
  },
  {
    id: "files-relative",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "crontab", ...workload },
    expect: { disposition: "NOT_COVERED", reason: "path_string_not_resolved" },
  },
  {
    id: "files-suffix-not-exact",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "/etc/crontab.bak", ...workload },
    expect: { disposition: "NOT_COVERED" },
  },
  {
    id: "files-dir-without-slash",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "/var/lib/vantio-proof", ...workload },
    expect: { disposition: "NOT_COVERED" },
  },
  {
    id: "files-dir-child",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "/var/lib/vantio-proof/agent", ...workload },
    expect: { disposition: "DENIED_BY_CITED_MECHANISM", effect: "EACCES" },
  },
  {
    id: "files-long-dir-child",
    surface: "files",
    attempt: { surface: "files", op: "open", path: `/var/lib/vantio-proof/${"a".repeat(80)}`, ...workload },
    expect: { disposition: "DENIED_BY_CITED_MECHANISM", effect: "EACCES" },
  },
  {
    id: "files-nul-truncated",
    surface: "files",
    attempt: { surface: "files", op: "open", path: "/etc/crontab\0extra", ...workload },
    expect: { disposition: "DENIED_BY_CITED_MECHANISM", effect: "EACCES" },
  },
  {
    id: "files-observe-label",
    surface: "files",
    attempt: { surface: "files", op: "observe_open", path: "/tmp/observe-only", ...workload },
    expect: { disposition: "LABELED_NOT_DENIED", mechanism_id: "openat_observe_label", effect: "NONE" },
  },
  {
    id: "files-observe-uid0",
    surface: "files",
    attempt: { surface: "files", op: "observe_open", path: "/tmp/observe-only", uid: 0, pid: 1 },
    expect: { disposition: "OBSERVED_ONLY", reason: "uid_0_not_labeled" },
  },
  {
    id: "files-observe-enforce-path",
    surface: "files",
    attempt: { surface: "files", op: "observe_open", path: "/etc/crontab", ...workload },
    expect: { disposition: "OBSERVED_ONLY", reason: "path_not_in_observe_maps" },
  },
  {
    id: "files-write-not-in-set",
    surface: "files",
    attempt: { surface: "files", op: "write", path: "/etc/crontab", ...workload },
    expect: { disposition: "NOT_COVERED", reason: "syscall_not_in_deny_set" },
  },
  {
    id: "files-mmap-not-in-set",
    surface: "files",
    attempt: { surface: "files", op: "mmap", path: "/etc/crontab", ...workload },
    expect: { disposition: "NOT_COVERED", reason: "syscall_not_in_deny_set" },
  },
  {
    id: "processes-execve",
    surface: "processes",
    attempt: { surface: "processes", op: "execve", path: "/bin/true" },
    expect: { disposition: "OBSERVED_ONLY", mechanism_id: "exec_tracepoints", residual: null },
  },
  {
    id: "processes-execve-enforce-path",
    surface: "processes",
    attempt: { surface: "processes", op: "execve", path: "/etc/crontab" },
    expect: { disposition: "OBSERVED_ONLY", residual: "execve_not_in_path_deny_set" },
  },
  {
    id: "processes-execveat",
    surface: "processes",
    attempt: { surface: "processes", op: "execveat", path: "/bin/true" },
    expect: { disposition: "OBSERVED_ONLY", program: "trace_execveat" },
  },
  {
    id: "processes-kill-off",
    surface: "processes",
    attempt: { surface: "processes", op: "kill_after_deny", path: "/etc/crontab", ...workload },
    expect: { disposition: "CITED_NO_SIGNAL", reason: "kill_mode_off" },
  },
  {
    id: "processes-kill-opt-in",
    surface: "processes",
    host: { kill_mode: 1 },
    attempt: { surface: "processes", op: "kill_after_deny", path: "/etc/crontab", ...workload },
    expect: { disposition: "CITED_OPT_IN_NOT_EXECUTED", signal: "SIGKILL", kernel_executed: false },
  },
  {
    id: "processes-kill-unlisted",
    surface: "processes",
    host: { kill_mode: 1 },
    attempt: { surface: "processes", op: "kill_after_deny", path: "/tmp/unlisted", ...workload },
    expect: { disposition: "CITED_NO_SIGNAL", reason: "path_not_denied" },
  },
  {
    id: "descendants-inherit",
    surface: "descendants",
    attempt: { surface: "descendants", op: "fork_inherit", trace_id: "0x0c1a" },
    expect: { disposition: "INHERIT_NO_WIDEN", child_trace_id: "0x0c1a", minted: false, widened: false },
  },
  {
    id: "descendants-no-mint",
    surface: "descendants",
    attempt: { surface: "descendants", op: "fork_inherit", trace_id: 0 },
    expect: { disposition: "INHERIT_NO_WIDEN", child_trace_id: 0, minted: false },
  },
  {
    id: "descendants-no-widen",
    surface: "descendants",
    attempt: { surface: "descendants", op: "child_widen_cidr", trace_id: "0x0c1a", cidr: "8.8.8.0/24" },
    expect: { disposition: "REJECTED_NOT_AN_AUTHORITY_INPUT", added: false, mechanism_id: "no_child_delegation_object" },
  },
  {
    id: "privileges-workload-mode",
    surface: "privileges",
    attempt: { surface: "privileges", op: "workload_set_mode" },
    expect: { disposition: "REJECTED_WORKLOAD", mode_before: "scoped", mode_after: "scoped" },
  },
  {
    id: "privileges-uid0-open",
    surface: "privileges",
    attempt: { surface: "privileges", op: "uid0_open", path: "/etc/crontab" },
    expect: { disposition: "NAMED_RESIDUAL", residual: "uid_0_excluded" },
  },
  {
    id: "credentials-token",
    surface: "credentials",
    attempt: { surface: "credentials", op: "present_token", token: "synthetic-not-a-secret" },
    expect: { disposition: "REJECTED_NOT_AN_AUTHORITY_INPUT", token_recorded: false, mechanism_id: "no_credential_hook" },
  },
  {
    id: "credentials-unlisted-file",
    surface: "credentials",
    attempt: { surface: "credentials", op: "open_path", path: "/etc/shadow", ...workload },
    expect: { disposition: "NOT_COVERED", mechanism_id: "no_credential_hook", credential_hook: false },
  },
  {
    id: "credentials-enrolled-path-is-file-rule",
    surface: "credentials",
    attempt: { surface: "credentials", op: "open_path", path: "/etc/crontab", ...workload },
    expect: { disposition: "DENIED_BY_CITED_MECHANISM", mechanism_id: "path_deny_kprobes", credential_hook: false },
  },
  {
    id: "namespaces-cgroup-enrolled",
    surface: "namespaces",
    attempt: { surface: "namespaces", op: "attribute_identity", kernel_tgid: 100, userspace_pid: 50, cgroup_id: 21 },
    expect: { disposition: "ENROLLED_BY_CGROUP_ID", enrolled: true, pid_used_as_key: false, offset_measured: false },
  },
  {
    id: "namespaces-pid-collision",
    surface: "namespaces",
    attempt: { surface: "namespaces", op: "attribute_identity", kernel_tgid: 21, userspace_pid: 21, cgroup_id: 0 },
    expect: { disposition: "NOT_COVERED", enrolled: false, reason: "cgroup_id_0", pid_used_as_key: false },
  },
  {
    id: "containers-enrolled-external",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_DROP", mechanism_id: "tc_scoped_egress", reason: "not_allowlisted" },
  },
  {
    id: "containers-unenrolled",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 99, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "cgroup_not_enrolled" },
  },
  {
    id: "containers-cgroup0",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 0, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "cgroup_id_0" },
  },
  {
    id: "containers-private",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "10.1.1.1", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "private_or_link_local" },
  },
  {
    id: "containers-exact-allow",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "1.1.1.1", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "exact_allow" },
  },
  {
    id: "containers-cidr-inside",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "1.1.1.255", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "cidr_allow" },
  },
  {
    id: "containers-cidr-outside",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "1.1.2.1", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_DROP", reason: "not_allowlisted" },
  },
  {
    id: "containers-audit",
    surface: "containers",
    host: { mode: "audit" },
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "audit_mode", protection_state_claimed: null },
  },
  {
    id: "containers-unknown-mode",
    surface: "containers",
    host: { mode: "banana" },
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "unknown_mode_does_not_drop", protection_state_claimed: null },
  },
  {
    id: "containers-node-wide",
    surface: "containers",
    host: { mode: "node_wide" },
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 99, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_DROP", reason: "not_allowlisted" },
  },
  {
    id: "containers-sever-before-allow",
    surface: "containers",
    host: { allow_exact_v4: ["1.1.1.1", "9.9.9.9"] },
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "9.9.9.9", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_DROP", reason: "sever_cidr" },
  },
  {
    id: "containers-port-before-allow",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "1.1.1.1", protocol: "tcp", port: 5432 },
    expect: { disposition: "CITED_DROP", reason: "blocked_tcp_port" },
  },
  {
    id: "containers-udp-port-ignored",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "1.1.1.1", protocol: "udp", port: 5432 },
    expect: { disposition: "CITED_ALLOW", reason: "exact_allow" },
  },
  {
    id: "containers-loopback",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "127.0.0.1", protocol: "tcp", port: 1 },
    expect: { disposition: "CITED_ALLOW", reason: "private_or_link_local" },
  },
  {
    id: "containers-172-below",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "172.15.255.255", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_DROP" },
  },
  {
    id: "containers-172-inside",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "172.16.0.0", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "private_or_link_local" },
  },
  {
    id: "containers-172-top",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "172.31.255.255", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "private_or_link_local" },
  },
  {
    id: "containers-172-above",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "172.32.0.0", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_DROP" },
  },
  {
    id: "containers-rfc1918-192",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "192.168.1.1", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "private_or_link_local" },
  },
  {
    id: "containers-link-local",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "169.254.1.1", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "private_or_link_local" },
  },
  {
    id: "containers-cgroup-skb-detached",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v4", plane: "cgroup_skb", cgroup_id: 21, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "NOT_COVERED", mechanism_id: "cgroup_skb_opt_in", reason: "cgroup_skb_not_attached" },
  },
  {
    id: "containers-cgroup-skb-detached-ignores-sever",
    surface: "containers",
    host: { severed_pids: [77] },
    attempt: { surface: "containers", op: "egress_v4", plane: "cgroup_skb", cgroup_id: 21, dest: "8.8.8.8", protocol: "tcp", port: 443, pid: 77 },
    expect: { disposition: "NOT_COVERED", mechanism_id: "cgroup_skb_opt_in", reason: "cgroup_skb_not_attached" },
  },
  {
    id: "containers-cgroup-skb-content-sever-without-enroll",
    surface: "containers",
    host: { cgroup_skb_attached: true, severed_pids: [77] },
    attempt: { surface: "containers", op: "egress_v4", plane: "cgroup_skb", cgroup_id: 99, dest: "1.1.1.1", protocol: "tcp", port: 443, pid: 77 },
    expect: { disposition: "CITED_DROP", mechanism_id: "tls_content_sever", reason: "tls_content_sever_pid" },
  },
  {
    id: "containers-cgroup-skb-audit-before-sever",
    surface: "containers",
    host: { cgroup_skb_attached: true, mode: "audit", severed_pids: [77] },
    attempt: { surface: "containers", op: "egress_v4", plane: "cgroup_skb", cgroup_id: 21, dest: "8.8.8.8", protocol: "tcp", port: 443, pid: 77 },
    expect: { disposition: "CITED_ALLOW", mechanism_id: "cgroup_skb_opt_in", reason: "audit_mode" },
  },
  {
    id: "containers-content-sever-after-enroll",
    surface: "containers",
    host: { severed_pids: [77] },
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "1.1.1.1", protocol: "tcp", port: 443, pid: 77 },
    expect: { disposition: "CITED_DROP", mechanism_id: "tls_content_sever", reason: "tls_content_sever_pid" },
  },
  {
    id: "containers-content-sever-unenrolled-passes",
    surface: "containers",
    host: { severed_pids: [77] },
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 0, dest: "8.8.8.8", protocol: "tcp", port: 443, pid: 77 },
    expect: { disposition: "CITED_ALLOW", reason: "cgroup_id_0" },
  },
  {
    id: "containers-cgroup-skb-ignores-enroll-map",
    surface: "containers",
    host: { cgroup_skb_attached: true },
    attempt: { surface: "containers", op: "egress_v4", plane: "cgroup_skb", cgroup_id: 99, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_DROP", mechanism_id: "cgroup_skb_opt_in", reason: "not_allowlisted" },
  },
  {
    id: "containers-cgroup-skb-attached",
    surface: "containers",
    host: { cgroup_skb_attached: true },
    attempt: { surface: "containers", op: "egress_v4", plane: "cgroup_skb", cgroup_id: 21, dest: "8.8.8.8", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_DROP", mechanism_id: "cgroup_skb_opt_in" },
  },
  {
    id: "containers-high-bit-cidr",
    surface: "containers",
    host: { allow_cidr_v4: ["200.1.2.0/24"], allow_exact_v4: [] },
    attempt: { surface: "containers", op: "egress_v4", plane: "tc", cgroup_id: 21, dest: "200.1.2.3", protocol: "tcp", port: 443 },
    expect: { disposition: "CITED_ALLOW", reason: "cidr_allow" },
  },
  {
    id: "containers-v6-link-local",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v6", plane: "tc", cgroup_id: 21, dest: "fe80::1" },
    expect: { disposition: "CITED_ALLOW", reason: "link_local" },
  },
  {
    id: "containers-v6-ula",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v6", plane: "tc", cgroup_id: 21, dest: "fc00::1" },
    expect: { disposition: "CITED_ALLOW", reason: "ula" },
  },
  {
    id: "containers-v6-external",
    surface: "containers",
    attempt: { surface: "containers", op: "egress_v6", plane: "tc", cgroup_id: 21, dest: "2001:db8::1" },
    expect: { disposition: "CITED_DROP", reason: "not_allowlisted" },
  },
  {
    id: "containers-v6-lpm-not-reimplemented",
    surface: "containers",
    host: { allow_cidr_v6: ["2001:db8::/32"] },
    attempt: { surface: "containers", op: "egress_v6", plane: "tc", cgroup_id: 21, dest: "2001:db8::1" },
    expect: { disposition: "NOT_REIMPLEMENTED", reason: "ipv6_lpm" },
  },
  {
    id: "devices-mknod",
    surface: "devices",
    attempt: { surface: "devices", op: "mknod", major: 1, minor: 3 },
    expect: { disposition: "NOT_COVERED", mechanism_id: "no_device_hook", reason: "device_number_not_a_hook" },
  },
  {
    id: "devices-unlisted-path",
    surface: "devices",
    attempt: { surface: "devices", op: "open_path", path: "/dev/mem", ...workload },
    expect: { disposition: "NOT_COVERED", mechanism_id: "no_device_hook", matches_device_number: false },
  },
  {
    id: "devices-enrolled-path-is-file-rule",
    surface: "devices",
    host: { enforce_exact: ["/etc/crontab", "/dev/mem"] },
    attempt: { surface: "devices", op: "open_path", path: "/dev/mem", ...workload },
    expect: { disposition: "DENIED_BY_CITED_MECHANISM", mechanism_id: "path_deny_kprobes", matches_device_number: false },
  },
  {
    id: "persistence-enrolled",
    surface: "persistence",
    attempt: { surface: "persistence", op: "open", path: "/etc/crontab", ...workload },
    expect: { disposition: "DENIED_BY_CITED_MECHANISM", mechanism_id: "persistence_via_path_deny", persistence_path_enrolled: true },
  },
  {
    id: "persistence-unlisted",
    surface: "persistence",
    attempt: { surface: "persistence", op: "open", path: "/lib/systemd/system/agent.service", ...workload },
    expect: { disposition: "NOT_COVERED", persistence_path_enrolled: false },
  },
  {
    id: "persistence-rename",
    surface: "persistence",
    attempt: { surface: "persistence", op: "rename", path: "/etc/crontab", path2: "/tmp/crontab", ...workload },
    expect: { disposition: "BEST_EFFORT_NOT_PROVED", decision_if_attached: "EACCES", persistence_path_enrolled: true },
  },
  {
    id: "resource-cpu",
    surface: "resource_use",
    attempt: { surface: "resource_use", op: "host_quota", kind: "cpu" },
    expect: { disposition: "NOT_COVERED", mechanism_id: "no_host_resource_hook", protection_state: "coverage_unknown" },
  },
  {
    id: "resource-spend-cap",
    surface: "resource_use",
    attempt: { surface: "resource_use", op: "gate_spend_cap", spend_cap_usd: 1 },
    expect: { disposition: "NOT_COVERED", different_plane: "APPLICATION_PATH", protection_state: "coverage_unknown" },
  },
  {
    id: "monitor-workload",
    surface: "monitor_disablement",
    attempt: { surface: "monitor_disablement", op: "unpin_maps", actor: "workload" },
    expect: { disposition: "REJECTED_WORKLOAD", mechanism_id: "workload_cannot_disable", mode_after: "scoped" },
  },
  {
    id: "monitor-privileged",
    surface: "monitor_disablement",
    attempt: { surface: "monitor_disablement", op: "unpin_maps", actor: "privileged" },
    expect: { disposition: "NAMED_RESIDUAL", residual: "privileged_pe_disable", state_changed_in_contract: false },
  },
  {
    id: "policy-workload",
    surface: "policy_tampering",
    attempt: { surface: "policy_tampering", actor: "workload", version: "9" },
    expect: { disposition: "REJECTED_WORKLOAD", contract_active: false, kernel_activated: false, maps_changed: false },
  },
  {
    id: "policy-root-unsigned",
    surface: "policy_tampering",
    attempt: { surface: "policy_tampering", actor: "privileged" },
    expect: { disposition: "NAMED_RESIDUAL", residual: "root_unsigned_map_load", contract_active: false, kernel_activated: false },
  },
  {
    id: "policy-attributed",
    surface: "policy_tampering",
    attempt: {
      surface: "policy_tampering",
      actor: "security",
      decision_id: "d1",
      version: "2",
      actor_id: "sec-1",
      rollback_target: "1",
    },
    expect: { disposition: "ACCEPTED_CONTRACT_RECORD_ONLY", kernel_activated: false, maps_changed: false, contract_active: true },
  },
  {
    id: "policy-missing-version",
    surface: "policy_tampering",
    attempt: { surface: "policy_tampering", actor: "security", decision_id: "d1", actor_id: "sec-1", rollback_target: "1" },
    expect: { disposition: "REJECTED_UNATTRIBUTED", contract_active: false, kernel_activated: false },
  },
];

module.exports = {
  CASES,
};
