"use strict";

const boundary = require("./boundary.cjs");
const { envelopesEqual, normalizeEnvelope, subsetViolations } = require("./envelope.cjs");
const engine = require("./engine.cjs");

module.exports = {
  APPROVAL_CLASSES: boundary.APPROVAL_CLASSES,
  AUDIENCE: boundary.AUDIENCE,
  COUNCIL_STATUS: boundary.COUNCIL_STATUS,
  COUNCIL_VERDICT: boundary.COUNCIL_VERDICT,
  DECISIONS: boundary.DECISIONS,
  DOMAINS: boundary.DOMAINS,
  MODULE_VERSION: boundary.MODULE_VERSION,
  PLAN_CLASSIFICATION_IN_TREE: boundary.PLAN_CLASSIFICATION_IN_TREE,
  PLAN_MERGE: boundary.PLAN_MERGE,
  PLAN_SITUATION: boundary.PLAN_SITUATION,
  POSTURE: boundary.POSTURE,
  PRODUCER_CLASSIFICATION: boundary.PRODUCER_CLASSIFICATION,
  RECOVERY_MODES: boundary.RECOVERY_MODES,
  REJECTED_ACTS: boundary.REJECTED_ACTS,
  REQUIREMENTS: boundary.REQUIREMENTS,
  RESERVED_POWERS: boundary.RESERVED_POWERS,
  SCHEMA_STATUS: boundary.SCHEMA_STATUS,
  SCHEMA_VERSION: boundary.SCHEMA_VERSION,
  STARTING_COMMIT: boundary.STARTING_COMMIT,
  acceptOpaqueIdentity: engine.acceptOpaqueIdentity,
  applyBillingOrSupport: engine.applyBillingOrSupport,
  changeOwnerSet: engine.changeOwnerSet,
  createCustomerHeldStore: engine.createCustomerHeldStore,
  displayGrant: engine.displayGrant,
  envelopesEqual,
  exportEvidence: engine.exportEvidence,
  foundRoot: engine.foundRoot,
  hashEvidence: engine.hashEvidence,
  inspect: engine.inspect,
  leaveFromCustomerHeldMaterial: engine.leaveFromCustomerHeldMaterial,
  nameRecoveryParty: engine.nameRecoveryParty,
  normalizeEnvelope,
  noteClock: engine.noteClock,
  noteSpawn: engine.noteSpawn,
  proposeGrant: engine.proposeGrant,
  quoteHostReport: engine.quoteHostReport,
  recordFreeze: engine.recordFreeze,
  recordHostIntent: engine.recordHostIntent,
  recordPolicyDecision: engine.recordPolicyDecision,
  recordRecognizedCustomer: engine.recordRecognizedCustomer,
  recordRollbackIntent: engine.recordRollbackIntent,
  recordUninstallIntent: engine.recordUninstallIntent,
  recover: engine.recover,
  refuseBreakglass: engine.refuseBreakglass,
  refuseDryRunActivation: engine.refuseDryRunActivation,
  refuseHostMark: engine.refuseHostMark,
  refuseSecondEnforcementEngine: engine.refuseSecondEnforcementEngine,
  removeWitness: engine.removeWitness,
  revokeGrant: engine.revokeGrant,
  setRecordStoreAvailable: engine.setRecordStoreAvailable,
  snapshot: engine.snapshot,
  subsetViolations,
};
