"use strict";

// PRIVATE | INERT | NOT SHIPPED | NO LIVE WRITER | NO LIVE READER | NO MIGRATION | NO STABLE SCHEMA

const POSTURE = Object.freeze([
  "PRIVATE",
  "INERT",
  "NOT_SHIPPED",
  "NO_LIVE_WRITER",
  "NO_LIVE_READER",
  "NO_MIGRATION",
  "NO_STABLE_SCHEMA",
]);

const AUDIENCE = "INTERNAL_RESTRICTED";
const SCHEMA_STATUS = "unstable-pre-1.0";
const SCHEMA_VERSION = 0;
const ADAPTER_VERSION = "0.0.0-unstable-pre-1.0";
const FUTURE_CLI_PLACEHOLDER = "PKG02-FUTURE-CLI-UNASSIGNED";
const UNICODE_PROFILE_ID = "PKG01-UCD-16.0.0";
const UNICODE_PROFILE_VERSION = "16.0.0";
const WITNESS_VALUE = "PKG01_OPTICS_GENERATED_WITNESS";

const OPTICS_STATUS = new Set([
  "OBSERVED",
  "NOT_OBSERVED",
  "UNSUPPORTED",
  "UNAVAILABLE",
  "APPLICATION_ERROR",
  "OPTICS_ERROR",
  "PARTIAL",
  "SUCCESS",
]);

const METHODS = new Set([
  "GET",
  "HEAD",
  "POST",
  "PUT",
  "DELETE",
  "CONNECT",
  "OPTIONS",
  "TRACE",
  "PATCH",
  "unknown",
]);

const ISSUE_LOCATIONS = new Set([
  "NONE",
  "NETWORK",
  "CUSTOMER_APPLICATION",
  "COVERAGE",
  "CONFIGURATION",
  "ENVIRONMENT",
  "OPTICS",
  "UNKNOWN",
  "PROVIDER_INTERACTION",
]);

const PRESERVED_ORIGINS = new Set([
  "IMPORTED",
  "SIMULATED_DEMO",
  "TEST_FIXTURE",
  "PRODUCT_HEALTH",
  "DERIVED_DIAGNOSTIC",
]);

const ORIGINAL_ORIGINS = new Set([
  "LEGACY_UNMARKED",
  "LOCAL_OBSERVATION",
  "SIMULATED_DEMO",
  "IMPORTED",
  "TEST_FIXTURE",
  "PRODUCT_HEALTH",
  "DERIVED_DIAGNOSTIC",
]);

const SAFE_VERSION = /^[A-Za-z0-9._+-]{1,32}$/;
const SAFE_NAME = /^[A-Za-z0-9_.:-]{1,80}$/;

module.exports = {
  ADAPTER_VERSION,
  AUDIENCE,
  FUTURE_CLI_PLACEHOLDER,
  ISSUE_LOCATIONS,
  METHODS,
  OPTICS_STATUS,
  ORIGINAL_ORIGINS,
  POSTURE,
  PRESERVED_ORIGINS,
  SAFE_NAME,
  SAFE_VERSION,
  SCHEMA_STATUS,
  SCHEMA_VERSION,
  UNICODE_PROFILE_ID,
  UNICODE_PROFILE_VERSION,
  WITNESS_VALUE,
};
