global(
  DefaultNetstreamDriver="gtls"
  DefaultNetstreamDriverCAFile="/certs/ca.pem"
  DefaultNetstreamDriverCertFile="/certs/server.pem"
  DefaultNetstreamDriverKeyFile="/certs/server.key"
)
module(load="imtcp")
input(type="imtcp" port="6514"
  StreamDriver.Name="gtls"
  StreamDriver.Mode="1"
  StreamDriver.AuthMode="x509/certvalid")
*.* action(type="omfile" file="/out/syslog.log")
