receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    timeout: 1s
connectors:
  spanmetrics:
    dimensions:
      - name: vantio.schema.version
    histogram:
      explicit:
        buckets: [1ms, 10ms, 100ms, 1s]
exporters:
  otlphttp/tempo:
    endpoint: http://host.docker.internal:4358
  otlphttp/loki:
    endpoint: http://host.docker.internal:3100/otlp
  prometheus:
    endpoint: 0.0.0.0:8889
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo, spanmetrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
