apiVersion: 1
datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://host.docker.internal:3202
    isDefault: true
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
