"use strict";

const fieldDimension = {
  accepted: "import_disposition",
  action: "observation_action",
  annotation_id: "record_identity",
  annotation_role: "annotation_payload",
  application_outcome_label: "workload_outcome",
  application_result: "validation_structure",
  application_status: "workload_outcome",
  arch: "process_identity",
  call_count: "coverage",
  cli_or_sdk_version: "version_identity",
  clock_quality: "timestamps_duration",
  compatibility: "validation_structure",
  completeness_impact: "completeness",
  completeness_inputs: "completeness",
  content_sha256: "record_identity",
  content_type: "destination_provider_identity",
  coverage_note: "coverage",
  created_at: "timestamps_duration",
  destination_host: "destination_provider_identity",
  destination_port: "destination_provider_identity",
  detail_code: "product_health_measurement",
  diagnostics: "validation_structure",
  disposition: "validation_structure",
  dropped_count: "drop_state",
  duplicate_of: "record_identity",
  duration_ms: "timestamps_duration",
  ended_at: "timestamps_duration",
  error_class: "http_network_outcomes",
  event_id: "record_identity",
  events: "validation_structure",
  evidence_origin: "evidence_origin_basis",
  failure_kind: "http_network_outcomes",
  fields: "validation_structure",
  health_impact: "optics_health",
  http_status: "http_network_outcomes",
  identity_conflict: "execution_identity",
  imported_at: "timestamps_duration",
  issue_location: "issue_location",
  issue_location_label: "issue_location",
  lifecycle: "attempt_lifecycle",
  mediation: "destination_provider_identity",
  method: "destination_provider_identity",
  name: "product_health_measurement",
  next_action_category: "derived_guidance",
  observed_at: "timestamps_duration",
  optics_health_impact: "optics_health",
  optics_status: "optics_health",
  original_evidence_origin: "evidence_origin_basis",
  parent_process_id: "process_identity",
  parent_run_id: "execution_identity",
  parent_span_id: "execution_identity",
  path: "destination_provider_identity",
  platform: "process_identity",
  process_id: "process_identity",
  producer: "execution_identity",
  producer_id: "execution_identity",
  producer_sequence: "execution_identity",
  provider_confidence: "destination_provider_identity",
  provider_id: "destination_provider_identity",
  provider_response_phrase: "dependency_outcome",
  reader_origin_label: "evidence_origin_basis",
  record: "validation_structure",
  record_emitted: "validation_structure",
  record_type: "schema_identity_status",
  remediation_code: "validation_structure",
  request_bytes: "http_network_outcomes",
  response_bytes: "http_network_outcomes",
  run_id: "execution_identity",
  runtime: "process_identity",
  runtime_version: "version_identity",
  sampling: "sampling",
  schema_status: "schema_identity_status",
  schema_status_seen: "schema_identity_status",
  schema_version: "version_identity",
  scheme: "destination_provider_identity",
  sequence: "execution_identity",
  session_id: "execution_identity",
  session_id_basis: "evidence_origin_basis",
  source_label: "record_identity",
  span_id: "execution_identity",
  started_at: "timestamps_duration",
  subject_event_id: "record_identity",
  subject_run_id: "execution_identity",
  text: "annotation_payload",
  trace_id: "execution_identity",
  trace_id_basis: "evidence_origin_basis",
  value: "product_health_measurement",
};

const recordFieldDimension = {
  "import_quarantine.reason_code": "import_disposition",
  "validation_result.reason_code": "validation_structure",
};

const compatibilityDimension = {
  action_taken: "observation_action",
  anonymousId: "prohibited_legacy",
  applicationLabel: "workload_outcome",
  applicationOutcomeLabel: "workload_outcome",
  auditMode: "legacy_surface",
  bytes_severed: "legacy_surface",
  "calls": "legacy_surface",
  "calls.action": "observation_action",
  "calls.applicationStatus": "workload_outcome",
  "calls.bytes": "http_network_outcomes",
  "calls.bytes_observed": "http_network_outcomes",
  "calls.error": "legacy_surface",
  "calls.failure_response": "dependency_outcome",
  "calls.hostname": "destination_provider_identity",
  "calls.ok": "legacy_boolean",
  "calls.opticsStatus": "optics_health",
  "calls.provider": "destination_provider_identity",
  "calls.redactions": "legacy_surface",
  "calls.status": "http_network_outcomes",
  "calls.ts": "timestamps_duration",
  cli_version: "version_identity",
  command: "prohibited_legacy",
  cost: "prohibited_legacy",
  coverage_gap: "coverage",
  data_note: "prohibited_legacy",
  destination: "destination_provider_identity",
  detail: "legacy_surface",
  est_spend_usd: "prohibited_legacy",
  event: "legacy_surface",
  eventPayload: "legacy_surface",
  free_mode: "prohibited_legacy",
  generated_at: "timestamps_duration",
  hostname_machine: "prohibited_legacy",
  httpStatus: "http_network_outcomes",
  machine: "prohibited_legacy",
  nextAction: "derived_guidance",
  nextActionCategory: "derived_guidance",
  node_version: "version_identity",
  optics_trace_witness: "evidence_origin_basis",
  opticsLabel: "optics_health",
  pid: "process_identity",
  plane: "prohibited_legacy",
  ppid: "process_identity",
  producer_version: "version_identity",
  providerName: "destination_provider_identity",
  providerResponse: "dependency_outcome",
  providerResponseLabel: "dependency_outcome",
  residual: "prohibited_legacy",
  status_labels: "prohibited_legacy",
  summary: "legacy_surface",
  "summary.applicationStatus": "workload_outcome",
  "summary.est_spend_usd": "prohibited_legacy",
  "summary.opticsStatus": "optics_health",
  "summary.total_bytes": "http_network_outcomes",
  target_host: "destination_provider_identity",
  timestamp_ns: "timestamps_duration",
  token_count: "prohibited_legacy",
  trace_id: "execution_identity",
  traceId: "execution_identity",
  traceparent: "execution_identity",
  unicode_profile_id: "version_identity",
  unicode_profile_version: "version_identity",
  upstreamService: "destination_provider_identity",
  usage: "prohibited_legacy",
  vantio_run_log: "legacy_surface",
  vantio_trace_id: "execution_identity",
  workflow: "prohibited_legacy",
};

const integrityBinding = {
  dimension: "integrity",
  record_type: "product_health",
  name_field: "name",
  name_value: "integrity_state",
  value_field: "value",
  allowed_values: ["OK", "FAILED", "UNKNOWN"],
  must_not_collapse_into: ["optics_health", "workload_outcome", "completeness", "coverage", "dependency_outcome"],
  note: "integrity_state is a product_health value family. It is not an optics_status token and not a catalog field of its own. PKG-02 does not add a field for it.",
};

const additionalDimensions = [
  "attempt_lifecycle",
  "observation_action",
  "product_health_measurement",
  "annotation_payload",
  "validation_structure",
  "derived_guidance",
  "import_disposition",
  "prohibited_legacy",
  "legacy_surface",
  "legacy_boolean",
];

const enumKeyByField = {
  application_outcome_label: "application_outcome_label",
  application_status: "application_status",
  arch: "arch",
  clock_quality: "clock_quality",
  coverage_note: "coverage_note",
  disposition: "dispositions",
  evidence_origin: "evidence_origin_writer",
  failure_kind: "failure_kind",
  identity_conflict: "identity_conflict",
  issue_location: "issue_location",
  lifecycle: "lifecycle",
  mediation: "mediation",
  method: "method",
  name: "product_health_name",
  next_action_category: "next_action_category",
  optics_status: "optics_status",
  original_evidence_origin: "original_evidence_origin",
  platform: "platform",
  producer: "recognized_producers",
  provider_confidence: "provider_confidence",
  provider_response_phrase: "provider_response_phrase",
  reader_origin_label: "original_evidence_origin",
  runtime: "runtime",
  scheme: "scheme",
  session_id_basis: "session_id_basis",
  trace_id_basis: "trace_id_basis",
};

function dimensionFor(recordType, name, role, liveName) {
  if (role === "compatibility") {
    if (!Object.prototype.hasOwnProperty.call(compatibilityDimension, liveName)) return null;
    return compatibilityDimension[liveName];
  }
  const specific = recordType + "." + name;
  if (Object.prototype.hasOwnProperty.call(recordFieldDimension, specific)) {
    return recordFieldDimension[specific];
  }
  if (!Object.prototype.hasOwnProperty.call(fieldDimension, name)) return null;
  return fieldDimension[name];
}

module.exports = {
  additionalDimensions,
  compatibilityDimension,
  dimensionFor,
  enumKeyByField,
  fieldDimension,
  integrityBinding,
  recordFieldDimension,
};
